### ISSUE TITLE
Showing class size for each run separately

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#166] opened 2018-05-22 10:56 UTC
The class sizes are currently visible for only one run,

![image](https://user-images.githubusercontent.com/3988444/40358441-8d12c2aa-5dbf-11e8-8b13-0681f3952418.png)

**Comment by thinkh** [comment] 2018-07-03 08:44
Duplicate of #155.

**Closed by thinkh** 2018-07-03 08:44 UTC
Labels: priority: low, status: duplicate, type: feature
