### ISSUE TITLE
Extend dataset/run chooser for multi-selection

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#66] opened 2018-02-26 12:34 UTC
The dataset chooser should be extended to select one or two datasets. 

Note that the suggestions for the second dataset depends on the selection of the first dataset in terms of the number of epochs or same dataset (CIFAR 10).

![image.png](https://images.zenhubusercontent.com/599562848f62dc7798c31c64/93a2978f-23af-4bb2-a86e-32b4baa88e89)

**Comment by gfrogat** [comment] 2018-03-20 06:35
duplicate of #63, #78 

resolved by #87

**Closed by gfrogat** 2018-03-20 06:35 UTC
Labels: priority: medium, status: duplicate, type: feature
